export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_ORDER = 'ADD_ORDER';
export const EMPTY_CART = 'EMPTY_CART';
export const ADD_PRODUCT_COUNT = 'ADD_PRODUCT_COUNT';
export const REMOVE_PRODUCT_COUNT = 'REMOVE_PRODUCT_COUNT';
